{% set version = "0.7.2" %}

package:
  name: glue-wwt
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/glue-wwt/glue-wwt-{{ version }}.tar.gz
  sha256: 2fbab973c24015f8a99bccddcfe08cf15fccd6e501d922056de0ab8e90f18eab

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:

  host:
    - python {{ python_min }}
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >={{ python_min }}
    - numpy
    - glue-core >=1.13.1
    - echo
    - qtpy
    - astropy-base
    - pywwt >=0.21.0
    - packaging
    - glue-qt
    - pyqtwebengine

test:
  requires:
    - python {{ python_min }}
  imports:
    - glue_wwt

about:
  home: https://github.com/glue-viz/glue-wwt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: WorldWide Telescope viewer plugin for glue

extra:
  recipe-maintainers:
    - astrofrog
