{% set version = "0.5" %}

package:
  name: glue-wwt
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/glue-wwt/glue-wwt-{{ version }}.tar.gz
  sha256: 4fe1e333c4f7830bd2df6fe6b48033448877c38bd5c1843b84306d03d1fd26e7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:

  host:
    - python >=3.6
    - pip
    - setuptools >=30.3
    - setuptools_scm

  run:
    - python >=3.6
    - numpy
    - glue-core >=1.0
    - echo
    - qtpy
    - astropy
    - pywwt >=0.6.0

test:
  imports:
    - glue_wwt

about:
  home: https://github.com/glue-viz/glue-wwt
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: WorldWide Telescope viewer plugin for glue

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
