{% set name = "glue-wwt" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glue-wwt-{{ version }}.tar.gz
  sha256: 2fbab973c24015f8a99bccddcfe08cf15fccd6e501d922056de0ab8e90f18eab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=61.2
    - setuptools-scm
  run:
    - python >=3.8
    - numpy
    - glue-core >=1.13.1
    - echo
    - qtpy
    - astropy
    - pywwt >=0.21.0
    - packaging
    - glue-qt
    - pyqtwebengine

test:
  imports:
    - glue_wwt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/glue-viz/glue-wwt
  summary: Glue WorldWide Telescope plugin
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
